### ISSUE TITLE
What's the next couple of top priorities for this project you would like help coding

### ISSUE THREAD

**Issue by aldricborders** [awesson/hieroglyph#1]
I wanted to start a project similar to yours and wouldnt mind helping out on this one instead. What's your short term road map look like?

**Comment by awesson** [comment]
Hey @aldricborders, I'm glad you're interested and thanks for the offer! However, for no fault of yours, I'd rather work on it alone.

It's just a side project of mine, so I don't spend a ton of time on it. I don't want to feel like I have to work on it and coordination isn't something I'm looking to deal with.

That said, if you have any questions getting started on your own project, just let me know. (I just put up my email on my profile.)

**Comment by aldricborders** [comment]
Thanks
